 DECLARE
 -- ATUALIZAR DIMENSOES
 PROCEDURE ATUALIZAR_DIMENCOES
 
 IS BEGIN
 
	 
	 -- ATUALIZAR DM_CURSOS COM BASE EM ESCOLA.CURSOS
	 MERGE INTO DM_CURSO DC
	 USING ESCOLA.CURSOS C ON ( C.COD_CURSO = DC.ID_CURSO )
	 
	 WHEN MATCHED THEN 
	 UPDATE SET 
	 DC.NOM_CURSO  = UPPER(C.NOM_CURSO)
	 	 
	 WHEN NOT MATCHED THEN 
	 
	 INSERT (DC.ID_CURSO, DC.NOM_CURSO)
	 VALUES (C.COD_CURSO, C.NOM_CURSO);
	
	-------------------------------------------------------------------------------------------------
	
	 -- ATUALIZAR DM_DEPARTAMENTO COM BASE EM ESCOLA.DEPARTAMENTOS
	 MERGE INTO DM_DEPARTAMENTO DDP
	 USING ESCOLA.DEPARTAMENTOS DP ON ( DP.COD_DPTO = DDP.ID_DPTO )
	 
	 WHEN MATCHED THEN 
	 UPDATE SET 
	 DDP.NOM_DPTO  = UPPER(DP.NOME_DPTO)
	 	 
	 WHEN NOT MATCHED THEN 
	 
	 
	 INSERT (DDP.ID_DPTO, DDP.NOM_DPTO)
	 VALUES (DP.COD_DPTO, DP.NOME_DPTO);
	
	-------------------------------------------------------------------------------------------------
	
	 -- ATUALIZAR DM_DISCIPLINA COM BASE EM ESCOLA.DISCIPLINAS
	 MERGE INTO DM_DISCIPLINA DD
	 USING ESCOLA.DISCIPLINAS D ON ( D.COD_DISC = DD.ID_DISC )
	 
	 WHEN MATCHED THEN 
	 UPDATE SET 
	 DD.NOME_DISC  = UPPER(D.NOME_DISC),
	 DD.CARGA_HORARIA = UPPER(D.CARGA_HORARIA)
	 	 
	 WHEN NOT MATCHED THEN 
	 
	 
	 INSERT (DD.ID_DISC, DD.NOME_DISC, DD.CARGA_HORARIA)
	 VALUES (D.COD_DISC, D.NOME_DISC, D.CARGA_HORARIA);
	
	-------------------------------------------------------------------------------------------------
	
	
	-- ATUALIZAR DM_TEMPO COM BASE EM ESCOLA.MATRICULAS
	 MERGE INTO DM_TEMPO DT
	 USING ( 
	 
	 SELECT DISTINCT 
	 SEMESTRE

 	 FROM ESCOLA.MATRICULAS
 	 
	 ) M
	 
	 
	 ON ( M.SEMESTRE = DT.ID_TEMPO )
	 
	 WHEN MATCHED THEN 
	 UPDATE SET 
	 DT.SEMESTRE = (M.SEMESTRE - 20110)
	 	 
	 WHEN NOT MATCHED THEN 
	 
	 
	 INSERT (DT.ID_TEMPO, DT.SEMESTRE)
	 VALUES (M.SEMESTRE, (M.SEMESTRE - 20110));
 	
	
END;
		
-- ATUALIZAR DIMENSOES
 PROCEDURE ATUALIZAR_FATOS
 
 IS BEGIN	
	
	 DELETE FROM FT_REPROVACAO;
	DELETE FROM FT_REPROVACAO_GC;
	
	MERGE INTO FT_REPROVACAO FTR
		USING 
		
		(SELECT
 SEMESTRE,
 COD_DISC,
 COD_CURSO,
 COD_DPTO,
 TOTAL_REP_DISC,
 TOTAL_MAT_ALU
 FROM
 (SELECT
 SEMESTRE,
 COD_DISC,
 COD_CURSO,
 COD_DPTO,
 COUNT(*) TOTAL_REP_DISC
 FROM
 ESCOLA.MATRICULAS JOIN ESCOLA.ALUNOS USING(MAT_ALU)
 JOIN ESCOLA.CURSOS USING(COD_CURSO)
 WHERE
 STATUS = 'R'
 GROUP BY
 SEMESTRE,
 COD_DISC,
 COD_CURSO,
 COD_DPTO)
 JOIN(SELECT
 SEMESTRE,
 COD_DISC,
 COD_CURSO,
 COD_DPTO,
 COUNT(*) TOTAL_MAT_ALU
 FROM
 ESCOLA.MATRICULAS JOIN ESCOLA.ALUNOS USING(MAT_ALU)
 JOIN ESCOLA.CURSOS USING(COD_CURSO)
 GROUP BY
 SEMESTRE,
 COD_DISC,
 COD_CURSO,
 COD_DPTO)
 USING(SEMESTRE, COD_DISC, COD_CURSO, COD_DPTO)) L
 
		ON (L.SEMESTRE = FTR.ID_TEMPO AND  L.COD_DISC = FTR.ID_DISC AND L.COD_CURSO = FTR.ID_CURSO AND L.COD_DPTO = FTR.ID_DPTO)
	
		 WHEN MATCHED THEN 
		 UPDATE SET 
		 FTR.TOTAL_REP_DISC = L.TOTAL_REP_DISC,
		 FTR.TOTAL_MAT_ALU = L.TOTAL_MAT_ALU
	 
		 WHEN NOT MATCHED THEN 
		 
		 INSERT (FTR.ID_TEMPO, FTR.ID_DISC, FTR.ID_CURSO, FTR.ID_DPTO, FTR.TOTAL_REP_DISC, FTR.TOTAL_MAT_ALU)
		 VALUES (L.SEMESTRE, L.COD_DISC, L.COD_CURSO, L.COD_DPTO, L.TOTAL_REP_DISC, L.TOTAL_MAT_ALU);
		
		
		-------------------------
		
		
		MERGE INTO FT_REPROVACAO_GC FL
		USING 
		
		(SELECT
 SEMESTRE,
 COD_DISC,
 TOTAL_REP_DISC,
 TOTAL_MAT_ALU,
 TOTAL_MAT,
 TOTAL_REPROVADOS
 FROM
 (SELECT
 SEMESTRE,
 COD_DISC,
 COUNT(*) TOTAL_REP_DISC
 FROM
 ESCOLA.MATRICULAS JOIN ESCOLA.ALUNOS USING(MAT_ALU)
 WHERE
 STATUS = 'R' AND COTISTA = 'S'
 GROUP BY
 SEMESTRE,
 COD_DISC)
 JOIN
 (SELECT
 SEMESTRE,
 COD_DISC,
 COUNT(*) TOTAL_MAT_ALU
 FROM
 ESCOLA.MATRICULAS JOIN ESCOLA.ALUNOS USING(MAT_ALU)
 WHERE
 COTISTA = 'S'
 GROUP BY
 SEMESTRE,
 COD_DISC)
 USING(SEMESTRE, COD_DISC)
 JOIN
 (SELECT
 SEMESTRE,
 COD_DISC,
 COUNT(*) TOTAL_MAT
 FROM
 ESCOLA.MATRICULAS
 GROUP BY
 SEMESTRE,
 COD_DISC)
 USING(SEMESTRE, COD_DISC)
 JOIN
 (SELECT
 SEMESTRE,
 COD_DISC,
 COUNT(*) TOTAL_REPROVADOS
 FROM
 ESCOLA.MATRICULAS
 WHERE
 STATUS = 'R'
 GROUP BY
 SEMESTRE,
 COD_DISC)
 USING(SEMESTRE, COD_DISC)) A
 
		ON (A.SEMESTRE = FL.ID_TEMPO AND  A.COD_DISC = FL.ID_DISC)
	
		 WHEN MATCHED THEN 
		 UPDATE SET 
		 FL.TOTAL_REP_COT_DISC = A.TOTAL_REP_DISC,
		 FL.TOTAL_MAT_ALU_COT = A.TOTAL_MAT_ALU,
		 FL.TOTAL_REPROVADOS = A.TOTAL_REPROVADOS,
		 FL.TOTAL_MAT = A.TOTAL_MAT
		 
	 
		 WHEN NOT MATCHED THEN 
		 
		 INSERT (FL.ID_TEMPO, FL.ID_DISC, FL.TOTAL_REP_COT_DISC, FL.TOTAL_MAT_ALU_COT, FL.TOTAL_REPROVADOS,  FL.TOTAL_MAT)
		 VALUES (A.SEMESTRE, A.COD_DISC, A.TOTAL_REP_DISC, A.TOTAL_MAT_ALU, A.TOTAL_REPROVADOS, A.TOTAL_MAT);
	 
	 
 END;
	
	BEGIN
  -- PROGRAMA PRINCIPAL	
  ATUALIZAR_DIMENCOES();
 ATUALIZAR_FATOS();
 
 END;

	







	
	

	